### PR TITLE
Define window functions on `hs.window` metatable

### LINKED ISSUE #72: Window bindings stopped working after updating Hammerspoon to 0.9.81
## Problem
I'm a mac user macOS Catalina 10.15.7
After updating Hammerspoon to 0.9.81 almost all my window bindings stopped working. The only working that I see is `{ {},         'space',  'centerWithFullHeight' }`

I checked Hammerspoon's console and it says the following:
```
2020-09-30 07:02:57: 07:02:57 ERROR:   LuaSkin: hs.hotkey callback: /Users/alexey/.hammerspoon/keyboard/windows.lua:261: attempt to call a nil value (field '?')
stack traceback:
	/Users/alexey/.hammerspoon/keyboard/windows.lua:261: in upvalue 'fn'
	/Users/alexey/.hammerspoon/keyboard/windows.lua:217: in function </Users/alexey/.hammerspoon/keyboard/windows.lua:215>
2020-09-30 07:02:58: 07:02:58     hotkey: Disabled hotkey F16
2020-09-30 07:02:58:              hotkey: Disabled previous hotkey ⌥W
2020-09-30 07:02:58:              hotkey: Re-enabled previous hotkey ⌥W
2020-09-30 07:02:58:              hotkey: Enabled hotkey F16
2020-09-30 07:02:58: 07:02:58 ERROR:   LuaSkin: hs.hotkey callback: /Users/alexey/.hammerspoon/keyboard/windows.lua:261: attempt to call a nil value (field '?')
stack traceback:
	/Users/alexey/.hammerspoon/keyboard/windows.lua:261: in upvalue 'fn'
	/Users/alexey/.hammerspoon/keyboard/windows.lua:217: in function </Users/alexey/.hammerspoon/keyboard/windows.lua:215>
2020-09-30 07:03:03: 07:03:03     hotkey: Disabled hotkey ⌃U
2020-09-30 07:03:08: 07:03:08     hotkey: Enabled hotkey ⌃U
```

What could be the problem?

### PR DESCRIPTION
**Pull request by landongrindheim**
Window functions started being defined on the metatable of the window object [in a recent commit](https://github.com/asmagill/hammerspoon/commit/4698dc669775fa85c3f55612805f9dc34c7ad19e). This change carries that pattern forward.

It might be worth noting that until now, the only place in this repository where functions are defined directly on Hammerspoon objects is in windows.lua.

Closes #72

### CODE REVIEW

File: hammerspoon/windows.lua [hunk 1]
```diff
@@ -1,11 +1,12 @@
 hs.window.animationDuration = 0
+window = hs.getObjectMetatable("hs.window")
```
Comment (landongrindheim) [inline hammerspoon/windows.lua:2]: I've debated naming this `windowMetatable`, since that's where the functions are being defined and, you know, that's what it is. However, I don't know that that name makes the code any clearer.

If this is viable for older versions of Hammerspoon (< 0.9.79), I'm open to renaming.

**Comment by jasonrudolph** [comment]
Thanks, @landongrindheim! :zap::cake:
